fetching:
  api_rate_limit_ms: 200  # Delay between API calls (milliseconds)
  batch_size: 400  # Number of calls before a pause
  batch_pause_duration: 300  # Pause duration in seconds (5 minutes)
  output_folder: 'stock_data'
  output_filename_format: 'stock_data_{date}.csv'

logging:
  level: "INFO"                     # Logging level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: "logs/stock_fetcher.log"  # Path to the log file

api:
  provider: "YahooFinance"          # Specify the API provider
  timeout: 10                       # Timeout in seconds for each API call
