fetching:
  ticker_file: "Input/tickers.txt"  # Path to the ticker list file
  batch_size: 400                   # Number of tickers to fetch per batch (now used internally)
  api_rate_limit_ms: 200            # API call rate limit in milliseconds per call
  output_folder: "Data"             # Folder to save the generated CSV files
  output_filename_format: "stock_data_{date}.csv"  # Output file name format with more generic name

logging:
  level: "INFO"                     # Logging level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: "logs/stock_fetcher.log"  # Path to the log file with more descriptive name

api:
  provider: "YahooFinance"          # Specify the API provider (for extensibility)
  max_retries: 2                    # Increased retry attempts
  timeout: 10                       # Timeout in seconds for each API call

file_format:
  csv:
    delimiter: ","                  # CSV file delimiter
    include_headers: true           # Whether to include headers in the CSV file
