fetching:
  batch_size: 100                   # Number of tickers to process before pausing
  api_rate_limit_ms: 200            # Delay between API calls in milliseconds
  output_folder: "Data"             # Folder to save the generated CSV files
  output_filename_format: "stock_data_{date}.csv"  # Output file name format

logging:
  level: "INFO"                     # Logging level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: "logs/stock_fetcher.log"  # Path to the log file

api:
  provider: "YahooFinance"          # Specify the API provider
  timeout: 10                       # Timeout in seconds for each API call
