name: Fetch Stock Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Debug directory structure
      - name: Debug directory structure
        run: |
          echo "Current directory: ${{ github.workspace }}"
          ls -R ${{ github.workspace }}

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Verify fetcher.py path
      - name: Verify fetcher.py existence
        run: |
          if [ ! -f Utilis/fetcher.py ]; then
            echo "Error: fetcher.py not found in Utilis/ directory."
            exit 1
          fi

      # Step 6: Run fetcher.py
      - name: Run fetcher.py
        run: |
          mkdir -p Data
          python Utilis/fetcher.py

      # Step 7: Debug Data directory
      - name: Debug Data directory
        run: |
          echo "Contents of Data directory:"
          ls -R Data || echo "Data directory not found or empty."

      # Step 8: Commit and push output
      - name: Commit and push output
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Data/*
          git status  # Debugging: Check for staged changes
          git commit -m "Update stock data [skip ci]" || echo "No changes to commit"
          git push origin HEAD || echo "Git push failed"
