name: Fetch Stock Data v3

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Specify Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the fetcher script
      - name: Run fetcher.py
        run: |
          mkdir -p Data
          python fetcher.py

      # Commit and push the updated CSV file
      - name: Commit and push output
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Data/stock_data.csv
          git commit -m "Update stock data [skip ci]" || echo "No changes to commit"
          git push origin HEAD
