name: Run Python Script Daily

on:
  schedule:
    - cron: '0 9 * * *'  # This will run at 09:00 UTC every day
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the version of Python you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies listed in requirements.txt

      - name: Run script
        run: python scripts_v5.py  # Adjust the path to your script
